---
- name: Install nginx package
  hosts: nginx
  package:
    name: nginx
    state: installed

- debug:
    var: role_path

- name: Upload rendered nginx.conf
  hosts: nginx
  template:
    src: "{{ role_path }}/templates/nginx.conf.j2"
    dest: "/etc/nginx/nginx.conf"


